language: node_js
node_js:
  - node
cache:
  yarn: true
  directories:
    - test/node_modules
script: cd test && yarn && npm test
after_script:
  - cd test && yarn codecov
notifications:
  email: false